services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - pgdatabase_volume:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_volume:/var/lib/pgadmin:rw
    ports:
      - 8080:80
    networks:
      - my_network

  # pipeline:
  #   build: 
  #     context: ./original_pipeline/
  #   command: ["--user=root", "--password=root", "--host=pgdatabase", "--port=5432", "--dbname=ny_taxi", "--table_name=yellow_taxi_data", "--csv_name=yellow_taxi_trip",  "--csv_url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"]
  #   depends_on:
  #     - pgdatabase
  #     - pgadmin
  #   networks:
  #     - my_network

networks:
  my_network:
    name: pg_network
    driver: bridge

volumes:
  pgdatabase_volume:
  pgadmin_volume:
